// Royalty-free, full-length tracks for the in-app Lounge Radio.
// Source: Kevin MacLeod (incompetech.com), licensed CC BY 4.0 - hot-linkable and
// range-seekable. Bucketed from the incompetech catalogue by genre/feel.
// ~56 tracks per station. Attribution shown in the player. Swap freely.

export interface RadioTrack {
  title: string;
  url: string;
}

export type RadioKey = "jazz" | "soul" | "lofi" | "focus";

export const RADIO_ATTRIBUTION = "Kevin MacLeod · incompetech.com · CC BY 4.0";

export interface RadioStation {
  key: RadioKey;
  label: string;
  tracks: RadioTrack[];
}

export const RADIO_STATIONS: RadioStation[] = [
  {
    key: "jazz",
    label: "Jazz",
    tracks: [
    { title: "Vibing Over Venus", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Vibing%20Over%20Venus.mp3" },
    { title: "Magic Escape Room", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Magic%20Escape%20Room.mp3" },
    { title: "Space Jazz", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Space%20Jazz.mp3" },
    { title: "Joey's Formal Waltz - Unscented", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Joey's%20Formal%20Waltz%20-%20Unscented.mp3" },
    { title: "On Hold for You", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/On%20Hold%20for%20You.mp3" },
    { title: "The Entertainer", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/The%20Entertainer.mp3" },
    { title: "Maple Leaf Rag", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Maple%20Leaf%20Rag.mp3" },
    { title: "Frogs Legs Rag", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Frogs%20Legs%20Rag.mp3" },
    { title: "Night in Venice", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Night%20in%20Venice.mp3" },
    { title: "Study And Relax", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Study%20And%20Relax.mp3" },
    { title: "Fuzzball Parade", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Fuzzball%20Parade.mp3" },
    { title: "Past Sadness", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Past%20Sadness.mp3" },
    { title: "Onion Capers", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Onion%20Capers.mp3" },
    { title: "Le Grand Chase", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Le%20Grand%20Chase.mp3" },
    { title: "Smooth Lovin", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Smooth%20Lovin.mp3" },
    { title: "Hard Boiled", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Hard%20Boiled.mp3" },
    { title: "Deuces", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Deuces.mp3" },
    { title: "Jazz Brunch", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Jazz%20Brunch.mp3" },
    { title: "Crinoline Dreams", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Crinoline%20Dreams.mp3" },
    { title: "Nouvelle Noel", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Nouvelle%20Noel.mp3" },
    { title: "Samba Isobel", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Samba%20Isobel.mp3" },
    { title: "Apero Hour", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Apero%20Hour.mp3" },
    { title: "Bossa Antigua", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Bossa%20Antigua.mp3" },
    { title: "Backbay Lounge", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Backbay%20Lounge.mp3" },
    { title: "Zazie", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Zazie.mp3" },
    { title: "Poppers and Prosecco", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Poppers%20and%20Prosecco.mp3" },
    { title: "Lobby Time", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Lobby%20Time.mp3" },
    { title: "Happy Happy Game Show", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Happy%20Happy%20Game%20Show.mp3" },
    { title: "OctoBlues", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/OctoBlues.mp3" },
    { title: "Spy Glass", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Spy%20Glass.mp3" },
    { title: "Wagon Wheel", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Wagon%20Wheel.mp3" },
    { title: "Lively Lumpsucker", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Lively%20Lumpsucker.mp3" },
    { title: "In Your Arms", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/In%20Your%20Arms.mp3" },
    { title: "Hep Cats", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Hep%20Cats.mp3" },
    { title: "Ultralounge", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Ultralounge.mp3" },
    { title: "Hyperfun", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Hyperfun.mp3" },
    { title: "On the Ground", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/On%20the%20Ground.mp3" },
    { title: "Rollin at 5", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Rollin%20at%205.mp3" },
    { title: "Rollin at 5 - electronic", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Rollin%20at%205%20-%20electronic.mp3" },
    { title: "Run Amok", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Run%20Amok.mp3" },
    { title: "George Street Shuffle", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/George%20Street%20Shuffle.mp3" },
    { title: "Local Forecast - Elevator", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Local%20Forecast%20-%20Elevator.mp3" },
    { title: "Local Forecast - Slower", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Local%20Forecast%20-%20Slower.mp3" },
    { title: "Local Forecast", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Local%20Forecast.mp3" },
    { title: "Batty McFaddin - Slower", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Batty%20McFaddin%20-%20Slower.mp3" },
    { title: "Sidewalk Shade - slower", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Sidewalk%20Shade%20-%20slower.mp3" },
    { title: "Sidewalk Shade", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Sidewalk%20Shade.mp3" },
    { title: "Fig Leaf Times Two", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Fig%20Leaf%20Times%20Two.mp3" },
    { title: "Mining by Moonlight", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Mining%20by%20Moonlight.mp3" },
    { title: "Groove Grove", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Groove%20Grove.mp3" },
    { title: "Batty McFaddin", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Batty%20McFaddin.mp3" },
    { title: "Cool Vibes", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Cool%20Vibes.mp3" },
    { title: "Airport Lounge", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Airport%20Lounge.mp3" },
    { title: "Hustle", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Hustle.mp3" },
    { title: "Merry Go - Distressed", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Merry%20Go%20-%20Distressed.mp3" },
    { title: "Merry Go Slower - Distressed", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Merry%20Go%20Slower%20-%20Distressed.mp3" },
    ],
  },
  {
    key: "soul",
    label: "Soul & Funk",
    tracks: [
    { title: "I Got a Stick Arr Bryan Teoh", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/I%20Got%20a%20Stick%20Arr%20Bryan%20Teoh.mp3" },
    { title: "I Got a Stick Feat James Gavins", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/I%20Got%20a%20Stick%20Feat%20James%20Gavins.mp3" },
    { title: "Funky Boxstep", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Funky%20Boxstep%20.mp3" },
    { title: "Aerosol of my Love", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Aerosol%20of%20my%20Love.mp3" },
    { title: "Del Rio Bravo", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Del%20Rio%20Bravo.mp3" },
    { title: "Realizer", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Realizer.mp3" },
    { title: "Celebration", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Celebration.mp3" },
    { title: "Verano Sensual", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Verano%20Sensual.mp3" },
    { title: "Glitter Blast", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Glitter%20Blast.mp3" },
    { title: "Arroz Con Pollo", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Arroz%20Con%20Pollo.mp3" },
    { title: "Loopster", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Loopster.mp3" },
    { title: "Werq", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Werq.mp3" },
    { title: "Android Sock Hop", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Android%20Sock%20Hop.mp3" },
    { title: "Bummin on Tremelo", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Bummin%20on%20Tremelo.mp3" },
    { title: "Sunday Dub", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Sunday%20Dub.mp3" },
    { title: "Shaving Mirror", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Shaving%20Mirror.mp3" },
    { title: "Wepa", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Wepa.mp3" },
    { title: "Miami Viceroy", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Miami%20Viceroy.mp3" },
    { title: "BossaBossa", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/BossaBossa.mp3" },
    { title: "ZigZag", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/ZigZag.mp3" },
    { title: "Chill Wave", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Chill%20Wave.mp3" },
    { title: "Casa Bossa Nova", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Casa%20Bossa%20Nova.mp3" },
    { title: "Blue Ska", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Blue%20Ska.mp3" },
    { title: "Cuban Sandwich", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Cuban%20Sandwich.mp3" },
    { title: "Upbeat Forever", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Upbeat%20Forever.mp3" },
    { title: "Funky Chunk", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Funky%20Chunk.mp3" },
    { title: "Disco Medusae", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Disco%20Medusae.mp3" },
    { title: "Pyro Flow", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Pyro%20Flow.mp3" },
    { title: "Carnivale Intrigue", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Carnivale%20Intrigue.mp3" },
    { title: "Your Call", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Your%20Call.mp3" },
    { title: "Life of Riley", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Life%20of%20Riley.mp3" },
    { title: "Electro Cabello", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Electro%20Cabello.mp3" },
    { title: "Guts and Bourbon", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Guts%20and%20Bourbon.mp3" },
    { title: "Aurea Carmina", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Aurea%20Carmina.mp3" },
    { title: "Disco con Tutti", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Disco%20con%20Tutti.mp3" },
    { title: "Beachfront Celebration", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Beachfront%20Celebration.mp3" },
    { title: "Got Funk", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Got%20Funk.mp3" },
    { title: "Overcast", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Overcast.mp3" },
    { title: "Bassa Island Game Loop", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Bassa%20Island%20Game%20Loop.mp3" },
    { title: "Funk Game Loop", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Funk%20Game%20Loop.mp3" },
    { title: "Hackbeat", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Hackbeat.mp3" },
    { title: "Aces High", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Aces%20High.mp3" },
    { title: "Honey Bee", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Honey%20Bee.mp3" },
    { title: "There It Is", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/There%20It%20Is.mp3" },
    { title: "Chee Zee Beach", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Chee%20Zee%20Beach.mp3" },
    { title: "Sunshine (version 2)", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Sunshine%20ver%202.mp3" },
    { title: "Clear Air", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Clear%20Air.mp3" },
    { title: "Disco Lounge", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Disco%20Lounge.mp3" },
    { title: "Somewhere Sunny (ver 2)", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Somewhere%20Sunny%20(ver%202).mp3" },
    { title: "Smooth Move", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Smooth%20Move.mp3" },
    { title: "Flutey Funk", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Flutey%20Funk.mp3" },
    { title: "Sunshine", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Sunshine%20A.mp3" },
    { title: "Somewhere Sunny", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Somewhere%20Sunny.mp3" },
    { title: "Happy Alley", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Happy%20Alley.mp3" },
    { title: "Funkorama", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Funkorama.mp3" },
    { title: "Back on Track", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Back%20on%20Track.mp3" },
    ],
  },
  {
    key: "lofi",
    label: "Lo-fi",
    tracks: [
    { title: "Morning", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Morning.mp3" },
    { title: "Joey's Formal Waltz - Scented", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Joey's%20Formal%20Waltz.mp3" },
    { title: "Late Night Radio", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Late%20Night%20Radio.mp3" },
    { title: "Ether Vox", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Ether%20Vox.mp3" },
    { title: "Almost Bliss", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Almost%20Bliss.mp3" },
    { title: "Angel Share", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Angel%20Share.mp3" },
    { title: "Dreamer", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Dreamer.mp3" },
    { title: "Carpe Diem", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Carpe%20Diem.mp3" },
    { title: "Immersed", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Immersed.mp3" },
    { title: "Fresh Air", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Fresh%20Air.mp3" },
    { title: "Suave Standpipe", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Suave%20Standpipe.mp3" },
    { title: "Fretless", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Fretless.mp3" },
    { title: "Kings of Tara", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Kings%20of%20Tara.mp3" },
    { title: "Universal", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Universal.mp3" },
    { title: "Dreams Become Real", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Dreams%20Become%20Real.mp3" },
    { title: "Infinite Perspective", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Infinite%20Perspective.mp3" },
    { title: "Carefree", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Carefree.mp3" },
    { title: "Colorless Aura", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Colorless%20Aura.mp3" },
    { title: "Dream Culture", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Dream%20Culture.mp3" },
    { title: "Perspectives", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Perspectives.mp3" },
    { title: "Summer Day", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Summer%20Day.mp3" },
    { title: "Easy Lemon (30 second)", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Easy%20Lemon%2030%20second.mp3" },
    { title: "Easy Lemon (60 second)", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Easy%20Lemon%2060%20second.mp3" },
    { title: "Easy Lemon", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Easy%20Lemon.mp3" },
    { title: "Danse Morialta", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Danse%20Morialta.mp3" },
    { title: "Avec Soin", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Avec%20Soin.mp3" },
    { title: "Calmant", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Calmant.mp3" },
    { title: "Facile", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Facile.mp3" },
    { title: "Pensif", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Pensif.mp3" },
    { title: "Wallpaper", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Wallpaper.mp3" },
    { title: "Enchanted Journey", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Enchanted%20Journey.mp3" },
    { title: "The Forest and the Trees", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/The%20Forest%20and%20the%20Trees.mp3" },
    { title: "Windswept", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Windswept.mp3" },
    { title: "Cattails", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Cattails.mp3" },
    { title: "Silver Blue Light", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Silver%20Blue%20Light.mp3" },
    { title: "When The Wind Blows", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/When%20The%20Wind%20Blows.mp3" },
    { title: "Feather Waltz", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Feather%20Waltz.mp3" },
    { title: "Resignation", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Resignation.mp3" },
    { title: "Thinking of You", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Thinking%20of%20You.mp3" },
    { title: "Swimmey Texture", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Swimmey%20Texture.mp3" },
    { title: "Blue Paint", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Blue%20Paint.mp3" },
    { title: "Smoother Move", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Smoother%20Move.mp3" },
    { title: "On the Passing of Time", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/On%20the%20Passing%20of%20Time.mp3" },
    { title: "Revival", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Revival.mp3" },
    { title: "Aretes", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Aretes.mp3" },
    { title: "Atlantean Twilight", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Atlantean%20Twilight.mp3" },
    { title: "Clear Waters", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Clear%20Waters.mp3" },
    { title: "Heartbreaking", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Heartbreaking.mp3" },
    { title: "Heartwarming", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Heartwarming.mp3" },
    { title: "Reminiscing", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Reminiscing.mp3" },
    { title: "Simple Duet", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Simple%20Duet.mp3" },
    { title: "Stoic Morning", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Stoic%20Morning.mp3" },
    { title: "There is Romance", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/There%20is%20Romance.mp3" },
    { title: "Touching Story", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Touching%20Story.mp3" },
    { title: "Two Together", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Two%20Together.mp3" },
    { title: "Winter Chimes", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Winter%20Chimes.mp3" },
    ],
  },
  {
    key: "focus",
    label: "Focus",
    tracks: [
    { title: "Galactic Rap", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Galactic%20Rap.mp3" },
    { title: "Equatorial Complex", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Equatorial%20Complex.mp3" },
    { title: "Evening", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Evening.mp3" },
    { title: "Starting Out Waltz Vivace", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Starting%20Out%20Waltz%20Vivace.mp3" },
    { title: "Starting Out Waltz Allegretto", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Starting%20Out%20Waltz%20Allegretto.mp3" },
    { title: "Pleasant Porridge", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Pleasant%20Porridge.mp3" },
    { title: "Bleeping Demo", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Bleeping%20Demo.mp3" },
    { title: "Limit 70", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Limit%2070.mp3" },
    { title: "Ebbs and Flows", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Ebbs%20and%20Flows.mp3" },
    { title: "Sincerely", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Sincerely.mp3" },
    { title: "Beauty Flow", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Beauty%20Flow.mp3" },
    { title: "Dream Catcher", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Dream%20Catcher.mp3" },
    { title: "Northern Glade", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Magic%20Scout%20-%20Nothern%20Glade.mp3" },
    { title: "Farm", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Magic%20Scout%20-%20Farm.mp3" },
    { title: "Manor", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Magic%20Scout%20-%20Manor.mp3" },
    { title: "Cottages", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Magic%20Scout%20-%20Cottages.mp3" },
    { title: "Getting it Done", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Getting%20it%20Done.mp3" },
    { title: "Townie Loop", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Townie%20Loop.mp3" },
    { title: "Jerry Five", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Jerry%20Five.mp3" },
    { title: "Laser Groove", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Laser%20Groove.mp3" },
    { title: "Doobly Doo", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Doobly%20Doo.mp3" },
    { title: "Digital Lemonade", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Digital%20Lemonade.mp3" },
    { title: "Airship Serenity", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Airship%20Serenity.mp3" },
    { title: "Soaring", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Soaring.mp3" },
    { title: "Eternity", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Eternity.mp3" },
    { title: "Inspired", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Inspired.mp3" },
    { title: "Leopard Print Elevator", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Leopard%20Print%20Elevator.mp3" },
    { title: "Relaxing Piano Music", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Relaxing%20Piano%20Music.mp3" },
    { title: "What Is Love", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/What%20Is%20Love.mp3" },
    { title: "Kawai Kitsune", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Kawai%20Kitsune.mp3" },
    { title: "Mesmerize", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Mesmerize.mp3" },
    { title: "Music for Manatees", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Music%20for%20Manatees.mp3" },
    { title: "White Lotus", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/White%20Lotus.mp3" },
    { title: "Pamgaea", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Pamgaea.mp3" },
    { title: "Clean Soul", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Clean%20Soul.mp3" },
    { title: "Inner Light", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Inner%20Light.mp3" },
    { title: "Space 1990-B", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Space%201990-B.mp3" },
    { title: "Space 1990", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Space%201990.mp3" },
    { title: "Peace of Mind", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Peace%20of%20Mind.mp3" },
    { title: "Wisps of Whorls", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Wisps%20of%20Whorls.mp3" },
    { title: "Reunited", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Reunited.mp3" },
    { title: "Healing", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Healing.mp3" },
    { title: "Brittle Rille", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Brittle%20Rille.mp3" },
    { title: "Drone in D", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Drone%20in%20D.mp3" },
    { title: "Light Thought var 2", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Light%20Thought%20var%202.mp3" },
    { title: "Light Thought var 1", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Light%20Thought%20var%201.mp3" },
    { title: "Promises to Keep", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Promises%20to%20Keep.mp3" },
    { title: "Over Under", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Over%20Under.mp3" },
    { title: "Bicycle", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Bicycle.mp3" },
    { title: "Wet Riffs", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Wet%20Riffs.mp3" },
    { title: "Isolated", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Isolated.mp3" },
    { title: "Autumn Day", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Autumn%20Day.mp3" },
    { title: "Organic Meditations One", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Organic%20Meditations%20One.mp3" },
    { title: "Organic Meditations Three", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Organic%20Meditations%20Three.mp3" },
    { title: "Organic Meditations Two", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Organic%20Meditations%20Two.mp3" },
    { title: "Eastminster", url: "https://incompetech.com/music/royalty-free/mp3-royaltyfree/Eastminster.mp3" },
    ],
  },
];

export const stationByKey = (key: RadioKey) =>
  RADIO_STATIONS.find((s) => s.key === key) ?? RADIO_STATIONS[0];
